### PR TITLE
Seperated environments for php56, php70 and php71

### PR DESCRIPTION
**Pull request by heiko-hardt**

### CODE REVIEW

**Review by Reamer — APPROVED** [review]
Okay

**Comment by Reamer** [comment]
@heiko-hardt please provide a PR which removes the old custom-typo3 Folder

**Comment by heichblatt** [comment]
Currently building:
- [custom-typo3-php56](https://hub.docker.com/r/publicisworldwide/jenkins-slave/builds/b5k8hfh9rqhdn5tulawnodd/)
- [custom-typo3-php70](https://hub.docker.com/r/publicisworldwide/jenkins-slave/builds/bczk3zkunyrekvxb5henunp/)
- [custom-typo3-php71](https://hub.docker.com/r/publicisworldwide/jenkins-slave/builds/b4x5rnawxefvqnjdt6rzamg/)

**Comment by heichblatt** [comment]
Builds [succeeded](https://hub.docker.com/r/publicisworldwide/jenkins-slave/builds/).

**Pull request merged**
